services:
  mysql-db:
    image: mysql:8.0
    container_name: activos_ti_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: activos_ti_db
      MYSQL_USER: user_node
      MYSQL_PASSWORD: node_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
volumes:
  mysql_data: